# -*- coding: utf-8 -*-
"""DA_Assignment_3_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EsugK9hcXLZevLO5myakWl1WjuGIqiPP

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**
"""

print(7**4);

"""** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **
"""

s = 'Hi there Sam!'
s.split()

s="Hi,there,dad!"
s.split()

"""** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.
"""

planet= "Earth"
diameter = 12742

print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

"""** Given this nested list, use indexing to grab the word "hello" **"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

"""** Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky **"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

"""** What is the main difference between a tuple and a list? **"""

# Tuple is immutable
#Tuples operations are safe.
#Tuples consumes less memory.

"""** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**
"""

def domainGet(email):
    print("Your domain is: " + email.split('@')[-1])

email = input("Please enter your email: >")
domainGet(email)

domainGet('user@domain.com')

"""** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **"""

def findDog(st):
    if 'dog' in st.lower():
        print("True")
    else:
        print("False")

st = "Is there a dog here?"
findDog(st)

findDog('Is there a dog here?')

"""** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **"""

def countDog(inp):
    dog = 0
    for x in inp.lower().split():
        if x == 'dog':
            dog += 1
    return dog
countdogs(value)

countDog('This dog runs faster than the other dog dude!')

"""### Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **
"""

def caught_speeding(speed, is_birthday):
    if is_birthday:
        speed = speed - 5
    if speed > 80:
        return 'Big Ticket'
    elif speed > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

caught_speeding(81,True)

caught_speeding(81,False)

"""Create an employee list with basic salary values(at least 5 values for 5 employees)  and using a for loop retreive each employee salary and calculate total salary expenditure. """

def employee_salary(basic):
  HRA=basic*0.1;
  DA=basic*0.05;
  PF=basic*0.12;  
  netsalary=basic+HRA+DA-PF;
  print("\nBasic:%lf \nHRA:%lf \nDA:%lf \nPF:%lf \nNet Salary:%lf" %(basic,HRA,DA,PF,netsalary));
  mylist=["rahul=10000","rajaraam=20000","kiruba=40000","kishore=15000","sandeep=30000"]
  employee=[rahul,rajaraam,kiruba,kishore,sandeep]
  print (mylist)
  print(netsalary)

"""Create two dictionaries in Python:

First one to contain fields as Empid,  Empname,  Basicpay

Second dictionary to contain fields as DeptName,  DeptId.

Combine both dictionaries. 
"""

def merge_twoDict(a, b): # define the merge_twoDict() function  
    return (a.update(b)) # append the second dictionary (b) to the first dictionary (a)   
  
a = {'Empid', 'Empname', 'Basicpay' }  
b = {'DeptName', 'DeptId'}           
merge_twoDict(a, b) # pass two dictionaries to merge_twoDict() function  
print("Merged Dictionaries is : ")  
print(a) # print the merge dictionaries